# Generated by Django 5.2.5 on 2025-08-28 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='resend_cooldown',
        ),
    ]
