# Generated by Django 5.2.5 on 2025-08-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_remove_otp_resend_cooldown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
    ]
